#!/usr/bin/env php
<?php

require_once __DIR__.'/../bootstrap.php';
require_once __DIR__.'/AppKernel.php';

use Symfony\Bundle\FrameworkBundle\Console\Application;
use Symfony\Component\Console\Input\ArgvInput;

use Symfony\Cmf\Bundle\ChainRoutingBundle\Tests\Functional\AppKernel;

$kernel = new AppKernel('default.yml');
$application = new Application($kernel);
$application->run();
